// Generated by wsdl2hed 
#ifndef __ARC_CENTRALISI_H__
#define __ARC_CENTRALISI_H__

#include <arc/message/Service.h>
#include <arc/delegation/DelegationInterface.h>
#include <arc/infosys/InformationInterface.h>

namespace CentralISI {

class CentralISIService: public Arc::Service
{

    public:
        CentralISIService(Arc::Config *cfg);
        virtual ~CentralISIService(void);
        virtual Arc::MCC_Status process(Arc::Message &inmsg, Arc::Message &outmsg);
    private:
        std::string db_path;
        Arc::NS ns;
        Arc::Logger logger;
        Arc::DelegationContainerSOAP delegation;
        Arc::InformationContainer infodoc;
        Arc::MCC_Status make_soap_fault(Arc::Message &outmsg);
        // Operations from WSDL
        Arc::MCC_Status Register(Arc::XMLNode &in, Arc::XMLNode &out);
        Arc::MCC_Status RemoveRegistrations(Arc::XMLNode &in, Arc::XMLNode &out);
        Arc::MCC_Status GetRegistrationStatuses(Arc::XMLNode &in, Arc::XMLNode &out);
        Arc::MCC_Status GetIISList(Arc::XMLNode &in, Arc::XMLNode &out);
        Arc::MCC_Status Get(Arc::XMLNode &in, Arc::XMLNode &out);

}; // class CentralISI
}; // namespace CentralISI
#endif // __ARC_CENTRALISI_H__
