// Generated by wsdl2hed 
#ifndef __ARC_CENTRALII_H__
#define __ARC_CENTRALII_H__

#include <arc/message/Service.h>
#include <arc/delegation/DelegationInterface.h>
#include <arc/infosys/InformationInterface.h>

namespace CentralII {

class CentralIIService: public Arc::Service
{

    public:
        CentralIIService(Arc::Config *cfg);
        virtual ~CentralIIService(void);
        virtual Arc::MCC_Status process(Arc::Message &inmsg, Arc::Message &outmsg);
    private:
        Arc::NS ns;
        Arc::Logger logger;
        Arc::DelegationContainerSOAP delegation;
        Arc::InformationContainer infodoc;
        Arc::MCC_Status make_soap_fault(Arc::Message &outmsg);
        // Operations from WSDL
        Arc::MCC_Status Register(Arc::XMLNode &in, Arc::XMLNode &out);
        Arc::MCC_Status RemoveRegistrations(Arc::XMLNode &in, Arc::XMLNode &out);
        Arc::MCC_Status GetRegistrationStatuses(Arc::XMLNode &in, Arc::XMLNode &out);
        Arc::MCC_Status GetIISList(Arc::XMLNode &in, Arc::XMLNode &out);

}; // class CentralII
}; // namespace CentralII
#endif // __ARC_CENTRALII_H__
