#!/bin/sh

make maintainer-clean

rm -fr include/.deps

rm -f nordugrid-arc-*.tar.gz

# Generated by aclocal.
rm -f aclocal.m4

# Copied by libtoolize
rm -f ltmain.sh
rm -f m4/libtool.m4
rm -f m4/ltoptions.m4
rm -f m4/ltsugar.m4
rm -f m4/ltversion.m4
rm -f m4/lt~obsolete.m4

# Generated by autoconf.
rm -f configure

# Generated by automake
find . -name Makefile.in -exec rm -f '{}' \;

# Copied by automake
rm -f config.guess config.sub install-sh missing depcomp

# Generated by gettext
rm -f po/*.gmo
rm -f po/nordugrid-arc.pot

# Copied by gettext/autopoint
rm -f config.rpath ABOUT-NLS
rm -f po/POTFILES.in

pofiles="
boldquot.sed
en@boldquot.header
en@quot.header
insert-header.sin
Makefile.in.in
Makevars.template
quot.sed
remove-potcdate.sin
Rules-quot
"

for i in $pofiles; do rm -f po/$i;done

m4files="
lib-link.m4
lib-prefix.m4
lib-ld.m4
lcmessage.m4
ulonglong.m4
progtest.m4
inttypes-pri.m4
uintmax_t.m4
stdint_h.m4
intdiv0.m4
po.m4
iconv.m4
isc-posix.m4
inttypes.m4
glibc21.m4
gettext.m4
inttypes_h.m4
codeset.m4
nls.m4
"
for i in $m4files; do rm -f m4/$i;done


