<?php

// Author: oxana.smirnova@hep.lu.se

// Some alias conversion

$curalias = htmlentities($curalias);

// hard-wired names:

/*
if ($curname == "grid.nbi.dk")                 $curalias = "NBI Grid";
if ($curname == "lscf.nbi.dk")                 $curalias = "LSCF";
if ($curname == "heppc08.nbi.dk")              $curalias = "Atlantis";
if ($curname == "morpheus.dcgc.dk")            $curalias = "Morpheus";
if ($curname == "hepax1.nbi.dk")               $curalias = "HEPAX";
if ($curname == "grendel.it.uu.se")            $curalias = "Grendel (NSC)";
if ($curname == "ingvar.nsc.liu.se")           $curalias = "Ingvar (NSC)";
if ($curname == "seth.hpc2n.umu.se")           $curalias = "Seth (HPC2N)";
if ($curname == "login-3.monolith.nsc.liu.se") $curalias = "Monolith (NSC)";
if ($curname == "ingrid.hpc2n.umu.se")         $curalias = "Ingrid (SweGrid,HPC2N)";
*/

//if ($curname == "ns1.nordita.dk")          $curalias = "NORDITA";
//if ($curname == "grid.uio.no")             $curalias = "UIO Grid";
//if ($curname == "grid.fi.uib.no")          $curalias = "FI Grid";
//if ($curname == "fire.ii.uib.no")          $curalias = "Parallab";
//if ($curname == "quark.hep.lu.se")         $curalias = "Quark Grid";
//if ($curname == "grid.tsl.uu.se")          $curalias = "TSL Grid";
//if ($curname == "grid.scfab.se")           $curalias = "SCFAB";
//if ($curname == "sleipner.byggmek.lth.se") $curalias = "Sleipner";
//if ($curname == "pc30.hip.helsinki.fi")    $curalias = "Kumpula";
//if ($curname == "pchip04.cern.ch")         $curalias = "Romu";

?>