<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="urn:echo"
 xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
 xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
 xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
 xmlns="http://schemas.xmlsoap.org/wsdl/"
 xmlns:echo="urn:echo">

<wsdl:types>
 <schema targetNamespace="urn:echo"
  xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>

  <simpleType name="say">
   <restriction base="xsd:string"/>
  </simpleType>

  <simpleType name="hear">
   <restriction base="xsd:string"/>
  </simpleType>
  
  <complexType name="echoRequest">
   <sequence>
    <element name="say" type="echo:say" minOccurs="1" maxOccurs="1"/>
   </sequence>
  </complexType>

  <complexType name="echoResponse">
   <sequence>
    <element name="hear" type="echo:hear" minOccurs="1" maxOccurs="1"/>
   </sequence>
  </complexType>
   
  <element name="echo" type="echo:echoRequest"/>
  <element name="echoResponse" type="echo:echoResponse"/>

 </schema>
</wsdl:types>

<wsdl:message name="echoRequest">
 <wsdl:part name="echoRequest" element="echo:echo"/>
</wsdl:message>

<wsdl:message name="echoResponse">
 <wsdl:part name="echoResponse" element="echo:echoResponse"/>
</wsdl:message>

<wsdl:portType name="echo">
 <wsdl:operation name="echo">
  <wsdl:input name="echoRequest" message="echo:echoRequest"/>
  <wsdl:output name="echoResponse" message="echo:echoResponse"/>
 </wsdl:operation>
</wsdl:portType>

<wsdl:binding name="echo" type="echo:echo">
 <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
 <wsdl:operation name="echo">
  <soap:operation soapAction="echo"/>
  <wsdl:input name="echoRequest">
   <soap:body use="literal"/>
  </wsdl:input>
  <wsdl:output name="echoResponse">
   <soap:body use="literal"/>
  </wsdl:output>
 </wsdl:operation>
</wsdl:binding>

<wsdl:service name="echo">
 <wsdl:port name="echo" binding="echo:echo">
  <soap:address location="http://localhost:80"/>
 </wsdl:port>
</wsdl:service>

</definitions>
