// JSDL
/* jsdl_soap.h
   Generated by wsdl2h 1.2.9d from jsdl_POSIXApplication.xsd jsdl_arc.xsd jsdl_complete.xsd and typemap.dat
   2007-06-28 20:00:00 GMT
   Copyright (C) 2001-2006 Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/* NOTE:

 - Compile this file with soapcpp2 to complete the code generation process.
 - Use soapcpp2 option -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
 - Use wsdl2h options -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control schema namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) to browse this file.
 - Use wsdl2h option -l to view the software license terms.

   DO NOT include this file directly into your project.
   Include only the soapcpp2-generated headers and source code files.
*/

//gsoapopt w

/******************************************************************************\
 *                                                                            *
 *                                                                            *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


// STL vector containers (use option -s to disable)
#import "stlvector.h"

/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

jsdlPOSIX = "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix"
jsdlARC = "http://www.nordugrid.org/ws/schemas/jsdl-arc"
jsdl = "http://schemas.ggf.org/jsdl/2005/11/jsdl"

*/

//gsoap jsdlPOSIX schema namespace:	http://schemas.ggf.org/jsdl/2005/11/jsdl-posix
//gsoap jsdlARC schema namespace:	http://www.nordugrid.org/ws/schemas/jsdl-arc
//gsoap jsdl  schema namespace:	http://schemas.ggf.org/jsdl/2005/11/jsdl
//gsoap jsdlPOSIX schema elementForm:	qualified
//gsoap jsdlPOSIX schema attributeForm:	unqualified
//gsoap jsdlARC schema form:	unqualified
//gsoap jsdl  schema elementForm:	qualified
//gsoap jsdl  schema attributeForm:	unqualified

/******************************************************************************\
 *                                                                            *
 * Schema Types                                                               *
 *                                                                            *
\******************************************************************************/


/// Primitive built-in type "xs:ID"
typedef std::string xsd__ID;

/// Primitive built-in type "xs:NCName"
typedef std::string xsd__NCName;

/// Primitive built-in type "xs:anyURI"
typedef std::string xsd__anyURI;

/// Primitive built-in type "xs:normalizedString"
typedef std::string xsd__normalizedString;


//  Forward declaration of class jsdlPOSIX__Environment_USCOREType.
class jsdlPOSIX__Environment_USCOREType;

//  Forward declaration of class jsdlPOSIX__Argument_USCOREType.
class jsdlPOSIX__Argument_USCOREType;

//  Forward declaration of class jsdlPOSIX__FileName_USCOREType.
class jsdlPOSIX__FileName_USCOREType;

//  Forward declaration of class jsdlPOSIX__DirectoryName_USCOREType.
class jsdlPOSIX__DirectoryName_USCOREType;

//  Forward declaration of class jsdlPOSIX__Limits_USCOREType.
class jsdlPOSIX__Limits_USCOREType;

//  Forward declaration of class jsdlPOSIX__UserName_USCOREType.
class jsdlPOSIX__UserName_USCOREType;

//  Forward declaration of class jsdlPOSIX__GroupName_USCOREType.
class jsdlPOSIX__GroupName_USCOREType;

//  Forward declaration of class jsdlPOSIX__POSIXApplication_USCOREType.
class jsdlPOSIX__POSIXApplication_USCOREType;

//  Forward declaration of class jsdlARC__Version_USCOREType.
class jsdlARC__Version_USCOREType;

//  Forward declaration of class jsdlARC__RunTimeEnvironment_USCOREType.
class jsdlARC__RunTimeEnvironment_USCOREType;

//  Forward declaration of class jsdlARC__Middleware_USCOREType.
class jsdlARC__Middleware_USCOREType;

//  Forward declaration of class jsdlARC__RemoteLogging_USCOREType.
class jsdlARC__RemoteLogging_USCOREType;

//  Forward declaration of class jsdlARC__CredentialServer_USCOREType.
class jsdlARC__CredentialServer_USCOREType;

//  Forward declaration of class jsdlARC__LocalLogging_USCOREType.
class jsdlARC__LocalLogging_USCOREType;

//  Forward declaration of class jsdlARC__AccessControl_USCOREType.
class jsdlARC__AccessControl_USCOREType;

//  Forward declaration of class jsdlARC__Notify_USCOREType.
class jsdlARC__Notify_USCOREType;

//  Forward declaration of class jsdlARC__CandidateTarget_USCOREType.
class jsdlARC__CandidateTarget_USCOREType;

//  Forward declaration of class jsdl__Boundary_USCOREType.
class jsdl__Boundary_USCOREType;

//  Forward declaration of class jsdl__Exact_USCOREType.
class jsdl__Exact_USCOREType;

//  Forward declaration of class jsdl__Range_USCOREType.
class jsdl__Range_USCOREType;

//  Forward declaration of class jsdl__RangeValue_USCOREType.
class jsdl__RangeValue_USCOREType;

//  Forward declaration of class jsdl__JobDefinition_USCOREType.
class jsdl__JobDefinition_USCOREType;

//  Forward declaration of class jsdl__JobDescription_USCOREType.
class jsdl__JobDescription_USCOREType;

//  Forward declaration of class jsdl__JobIdentification_USCOREType.
class jsdl__JobIdentification_USCOREType;

//  Forward declaration of class jsdl__Application_USCOREType.
class jsdl__Application_USCOREType;

//  Forward declaration of class jsdl__Resources_USCOREType.
class jsdl__Resources_USCOREType;

//  Forward declaration of class jsdl__CandidateHosts_USCOREType.
class jsdl__CandidateHosts_USCOREType;

//  Forward declaration of class jsdl__CPUArchitecture_USCOREType.
class jsdl__CPUArchitecture_USCOREType;

//  Forward declaration of class jsdl__FileSystem_USCOREType.
class jsdl__FileSystem_USCOREType;

//  Forward declaration of class jsdl__OperatingSystem_USCOREType.
class jsdl__OperatingSystem_USCOREType;

//  Forward declaration of class jsdl__OperatingSystemType_USCOREType.
class jsdl__OperatingSystemType_USCOREType;

//  Forward declaration of class jsdl__DataStaging_USCOREType.
class jsdl__DataStaging_USCOREType;

//  Forward declaration of class jsdl__SourceTarget_USCOREType.
class jsdl__SourceTarget_USCOREType;

/// "http://www.nordugrid.org/ws/schemas/jsdl-arc":GMState_Type is a simpleType restriction of xs:string.
/// Note: enum values are prefixed with 'jsdlARC__GMState_USCOREType' to avoid name clashes, please use wsdl2h option -e to omit this prefix
enum jsdlARC__GMState_USCOREType
{
	jsdlARC__GMState_USCOREType__ACCEPTED,	///< xs:string value="ACCEPTED"
	jsdlARC__GMState_USCOREType__PREPARING,	///< xs:string value="PREPARING"
	jsdlARC__GMState_USCOREType__SUBMIT,	///< xs:string value="SUBMIT"
	jsdlARC__GMState_USCOREType__INLRMS,	///< xs:string value="INLRMS"
	jsdlARC__GMState_USCOREType__FINISHING,	///< xs:string value="FINISHING"
	jsdlARC__GMState_USCOREType__FINISHED,	///< xs:string value="FINISHED"
	jsdlARC__GMState_USCOREType__DELETED,	///< xs:string value="DELETED"
	jsdlARC__GMState_USCOREType__CANCELING,	///< xs:string value="CANCELING"
};

/// "http://www.nordugrid.org/ws/schemas/jsdl-arc":SessionType_Type is a simpleType restriction of xs:string.
/// Note: enum values are prefixed with 'jsdlARC__SessionType_USCOREType' to avoid name clashes, please use wsdl2h option -e to omit this prefix
enum jsdlARC__SessionType_USCOREType
{
	jsdlARC__SessionType_USCOREType__INTERNAL,	///< xs:string value="INTERNAL"
	jsdlARC__SessionType_USCOREType__LIMITED,	///< xs:string value="LIMITED"
	jsdlARC__SessionType_USCOREType__READONLY,	///< xs:string value="READONLY"
	jsdlARC__SessionType_USCOREType__FULL,	///< xs:string value="FULL"
};

/// "http://www.nordugrid.org/ws/schemas/jsdl-arc":IsExecutable_Type is a simpleType restriction of xs:boolean.
typedef bool jsdlARC__IsExecutable_USCOREType;

/// "http://www.nordugrid.org/ws/schemas/jsdl-arc":FileParameters_Type is a simpleType restriction of xs:string.
typedef std::string jsdlARC__FileParameters_USCOREType;

/// "http://www.nordugrid.org/ws/schemas/jsdl-arc":JoinOutputs_Type is a simpleType restriction of xs:boolean.
typedef bool jsdlARC__JoinOutputs_USCOREType;

/// "http://www.nordugrid.org/ws/schemas/jsdl-arc":Reruns_Type is a simpleType restriction of xs:integer.
typedef int jsdlARC__Reruns_USCOREType;

/// "http://www.nordugrid.org/ws/schemas/jsdl-arc":AccessControlType_Type is a simpleType restriction of xs:string.
/// Note: enum values are prefixed with 'jsdlARC__AccessControlType_USCOREType' to avoid name clashes, please use wsdl2h option -e to omit this prefix
enum jsdlARC__AccessControlType_USCOREType
{
	jsdlARC__AccessControlType_USCOREType__GACL,	///< xs:string value="GACL"
};

/// "http://www.nordugrid.org/ws/schemas/jsdl-arc":NotificationType_Type is a simpleType restriction of xs:string.
/// Note: enum values are prefixed with 'jsdlARC__NotificationType_USCOREType' to avoid name clashes, please use wsdl2h option -e to omit this prefix
enum jsdlARC__NotificationType_USCOREType
{
	jsdlARC__NotificationType_USCOREType__Email,	///< xs:string value="Email"
};

/// "http://www.nordugrid.org/ws/schemas/jsdl-arc":SessionLifeTime_Type is a simpleType restriction of xs:long.
typedef LONG64 jsdlARC__SessionLifeTime_USCOREType;

/// "http://www.nordugrid.org/ws/schemas/jsdl-arc":GridTimeLimit_Type is a simpleType restriction of xs:positiveInteger.
typedef unsigned int jsdlARC__GridTimeLimit_USCOREType;

/// "http://www.nordugrid.org/ws/schemas/jsdl-arc":Time_Type is a simpleType restriction of xs:dateTime.
typedef time_t jsdlARC__Time_USCOREType;

/// "http://schemas.ggf.org/jsdl/2005/11/jsdl":ProcessorArchitectureEnumeration is a simpleType restriction of xs:string.
/// Note: enum values are prefixed with 'jsdl__ProcessorArchitectureEnumeration' to avoid name clashes, please use wsdl2h option -e to omit this prefix
enum jsdl__ProcessorArchitectureEnumeration
{
	jsdl__ProcessorArchitectureEnumeration__sparc,	///< xs:string value="sparc"
	jsdl__ProcessorArchitectureEnumeration__powerpc,	///< xs:string value="powerpc"
	jsdl__ProcessorArchitectureEnumeration__x86,	///< xs:string value="x86"
	jsdl__ProcessorArchitectureEnumeration__x86_USCORE32,	///< xs:string value="x86_32"
	jsdl__ProcessorArchitectureEnumeration__x86_USCORE64,	///< xs:string value="x86_64"
	jsdl__ProcessorArchitectureEnumeration__parisc,	///< xs:string value="parisc"
	jsdl__ProcessorArchitectureEnumeration__mips,	///< xs:string value="mips"
	jsdl__ProcessorArchitectureEnumeration__ia64,	///< xs:string value="ia64"
	jsdl__ProcessorArchitectureEnumeration__arm,	///< xs:string value="arm"
	jsdl__ProcessorArchitectureEnumeration__other,	///< xs:string value="other"
};

/// "http://schemas.ggf.org/jsdl/2005/11/jsdl":OperatingSystemTypeEnumeration is a simpleType restriction of xs:string.
/// Note: enum values are prefixed with 'jsdl__OperatingSystemTypeEnumeration' to avoid name clashes, please use wsdl2h option -e to omit this prefix
enum jsdl__OperatingSystemTypeEnumeration
{
	jsdl__OperatingSystemTypeEnumeration__Unknown,	///< xs:string value="Unknown"
	jsdl__OperatingSystemTypeEnumeration__MACOS,	///< xs:string value="MACOS"
	jsdl__OperatingSystemTypeEnumeration__ATTUNIX,	///< xs:string value="ATTUNIX"
	jsdl__OperatingSystemTypeEnumeration__DGUX,	///< xs:string value="DGUX"
	jsdl__OperatingSystemTypeEnumeration__DECNT,	///< xs:string value="DECNT"
	jsdl__OperatingSystemTypeEnumeration__Tru64_USCOREUNIX,	///< xs:string value="Tru64_UNIX"
	jsdl__OperatingSystemTypeEnumeration__OpenVMS,	///< xs:string value="OpenVMS"
	jsdl__OperatingSystemTypeEnumeration__HPUX,	///< xs:string value="HPUX"
	jsdl__OperatingSystemTypeEnumeration__AIX,	///< xs:string value="AIX"
	jsdl__OperatingSystemTypeEnumeration__MVS,	///< xs:string value="MVS"
	jsdl__OperatingSystemTypeEnumeration__OS400,	///< xs:string value="OS400"
	jsdl__OperatingSystemTypeEnumeration__OS_USCORE2,	///< xs:string value="OS_2"
	jsdl__OperatingSystemTypeEnumeration__JavaVM,	///< xs:string value="JavaVM"
	jsdl__OperatingSystemTypeEnumeration__MSDOS,	///< xs:string value="MSDOS"
	jsdl__OperatingSystemTypeEnumeration__WIN3x,	///< xs:string value="WIN3x"
	jsdl__OperatingSystemTypeEnumeration__WIN95,	///< xs:string value="WIN95"
	jsdl__OperatingSystemTypeEnumeration__WIN98,	///< xs:string value="WIN98"
	jsdl__OperatingSystemTypeEnumeration__WINNT,	///< xs:string value="WINNT"
	jsdl__OperatingSystemTypeEnumeration__WINCE,	///< xs:string value="WINCE"
	jsdl__OperatingSystemTypeEnumeration__NCR3000,	///< xs:string value="NCR3000"
	jsdl__OperatingSystemTypeEnumeration__NetWare,	///< xs:string value="NetWare"
	jsdl__OperatingSystemTypeEnumeration__OSF,	///< xs:string value="OSF"
	jsdl__OperatingSystemTypeEnumeration__DC_USCOREOS,	///< xs:string value="DC_OS"
	jsdl__OperatingSystemTypeEnumeration__Reliant_USCOREUNIX,	///< xs:string value="Reliant_UNIX"
	jsdl__OperatingSystemTypeEnumeration__SCO_USCOREUnixWare,	///< xs:string value="SCO_UnixWare"
	jsdl__OperatingSystemTypeEnumeration__SCO_USCOREOpenServer,	///< xs:string value="SCO_OpenServer"
	jsdl__OperatingSystemTypeEnumeration__Sequent,	///< xs:string value="Sequent"
	jsdl__OperatingSystemTypeEnumeration__IRIX,	///< xs:string value="IRIX"
	jsdl__OperatingSystemTypeEnumeration__Solaris,	///< xs:string value="Solaris"
	jsdl__OperatingSystemTypeEnumeration__SunOS,	///< xs:string value="SunOS"
	jsdl__OperatingSystemTypeEnumeration__U6000,	///< xs:string value="U6000"
	jsdl__OperatingSystemTypeEnumeration__ASERIES,	///< xs:string value="ASERIES"
	jsdl__OperatingSystemTypeEnumeration__TandemNSK,	///< xs:string value="TandemNSK"
	jsdl__OperatingSystemTypeEnumeration__TandemNT,	///< xs:string value="TandemNT"
	jsdl__OperatingSystemTypeEnumeration__BS2000,	///< xs:string value="BS2000"
	jsdl__OperatingSystemTypeEnumeration__LINUX,	///< xs:string value="LINUX"
	jsdl__OperatingSystemTypeEnumeration__Lynx,	///< xs:string value="Lynx"
	jsdl__OperatingSystemTypeEnumeration__XENIX,	///< xs:string value="XENIX"
	jsdl__OperatingSystemTypeEnumeration__VM,	///< xs:string value="VM"
	jsdl__OperatingSystemTypeEnumeration__Interactive_USCOREUNIX,	///< xs:string value="Interactive_UNIX"
	jsdl__OperatingSystemTypeEnumeration__BSDUNIX,	///< xs:string value="BSDUNIX"
	jsdl__OperatingSystemTypeEnumeration__FreeBSD,	///< xs:string value="FreeBSD"
	jsdl__OperatingSystemTypeEnumeration__NetBSD,	///< xs:string value="NetBSD"
	jsdl__OperatingSystemTypeEnumeration__GNU_USCOREHurd,	///< xs:string value="GNU_Hurd"
	jsdl__OperatingSystemTypeEnumeration__OS9,	///< xs:string value="OS9"
	jsdl__OperatingSystemTypeEnumeration__MACH_USCOREKernel,	///< xs:string value="MACH_Kernel"
	jsdl__OperatingSystemTypeEnumeration__Inferno,	///< xs:string value="Inferno"
	jsdl__OperatingSystemTypeEnumeration__QNX,	///< xs:string value="QNX"
	jsdl__OperatingSystemTypeEnumeration__EPOC,	///< xs:string value="EPOC"
	jsdl__OperatingSystemTypeEnumeration__IxWorks,	///< xs:string value="IxWorks"
	jsdl__OperatingSystemTypeEnumeration__VxWorks,	///< xs:string value="VxWorks"
	jsdl__OperatingSystemTypeEnumeration__MiNT,	///< xs:string value="MiNT"
	jsdl__OperatingSystemTypeEnumeration__BeOS,	///< xs:string value="BeOS"
	jsdl__OperatingSystemTypeEnumeration__HP_USCOREMPE,	///< xs:string value="HP_MPE"
	jsdl__OperatingSystemTypeEnumeration__NextStep,	///< xs:string value="NextStep"
	jsdl__OperatingSystemTypeEnumeration__PalmPilot,	///< xs:string value="PalmPilot"
	jsdl__OperatingSystemTypeEnumeration__Rhapsody,	///< xs:string value="Rhapsody"
	jsdl__OperatingSystemTypeEnumeration__Windows_USCORE2000,	///< xs:string value="Windows_2000"
	jsdl__OperatingSystemTypeEnumeration__Dedicated,	///< xs:string value="Dedicated"
	jsdl__OperatingSystemTypeEnumeration__OS_USCORE390,	///< xs:string value="OS_390"
	jsdl__OperatingSystemTypeEnumeration__VSE,	///< xs:string value="VSE"
	jsdl__OperatingSystemTypeEnumeration__TPF,	///< xs:string value="TPF"
	jsdl__OperatingSystemTypeEnumeration__Windows_USCORER_USCOREMe,	///< xs:string value="Windows_R_Me"
	jsdl__OperatingSystemTypeEnumeration__Caldera_USCOREOpen_USCOREUNIX,	///< xs:string value="Caldera_Open_UNIX"
	jsdl__OperatingSystemTypeEnumeration__OpenBSD,	///< xs:string value="OpenBSD"
	jsdl__OperatingSystemTypeEnumeration__Not_USCOREApplicable,	///< xs:string value="Not_Applicable"
	jsdl__OperatingSystemTypeEnumeration__Windows_USCOREXP,	///< xs:string value="Windows_XP"
	jsdl__OperatingSystemTypeEnumeration__z_USCOREOS,	///< xs:string value="z_OS"
	jsdl__OperatingSystemTypeEnumeration__other,	///< xs:string value="other"
};

/// "http://schemas.ggf.org/jsdl/2005/11/jsdl":FileSystemTypeEnumeration is a simpleType restriction of xs:string.
/// Note: enum values are prefixed with 'jsdl__FileSystemTypeEnumeration' to avoid name clashes, please use wsdl2h option -e to omit this prefix
enum jsdl__FileSystemTypeEnumeration
{
	jsdl__FileSystemTypeEnumeration__swap,	///< xs:string value="swap"
	jsdl__FileSystemTypeEnumeration__temporary,	///< xs:string value="temporary"
	jsdl__FileSystemTypeEnumeration__spool,	///< xs:string value="spool"
	jsdl__FileSystemTypeEnumeration__normal,	///< xs:string value="normal"
};

/// "http://schemas.ggf.org/jsdl/2005/11/jsdl":CreationFlagEnumeration is a simpleType restriction of xs:string.
/// Note: enum values are prefixed with 'jsdl__CreationFlagEnumeration' to avoid name clashes, please use wsdl2h option -e to omit this prefix
enum jsdl__CreationFlagEnumeration
{
	jsdl__CreationFlagEnumeration__overwrite,	///< xs:string value="overwrite"
	jsdl__CreationFlagEnumeration__append,	///< xs:string value="append"
	jsdl__CreationFlagEnumeration__dontOverwrite,	///< xs:string value="dontOverwrite"
};

/// "http://schemas.ggf.org/jsdl/2005/11/jsdl":Description_Type is a simpleType restriction of xs:string.
typedef std::string jsdl__Description_USCOREType;

/// "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":POSIXApplication_Type is a complexType.
class jsdlPOSIX__POSIXApplication_USCOREType
{ public:
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":Executable.
    jsdlPOSIX__FileName_USCOREType*      Executable                     0;	///< Optional element.
/// Vector of jsdlPOSIX__Argument_USCOREType* with length 0..unbounded
    std::vector<jsdlPOSIX__Argument_USCOREType*> Argument                       0;
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":Input.
    jsdlPOSIX__FileName_USCOREType*      Input                          0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":Output.
    jsdlPOSIX__FileName_USCOREType*      Output                         0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":Error.
    jsdlPOSIX__FileName_USCOREType*      Error                          0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":WorkingDirectory.
    jsdlPOSIX__DirectoryName_USCOREType*  WorkingDirectory               0;	///< Optional element.
/// Vector of jsdlPOSIX__Environment_USCOREType* with length 0..unbounded
    std::vector<jsdlPOSIX__Environment_USCOREType*> Environment                    0;
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":WallTimeLimit.
    jsdlPOSIX__Limits_USCOREType*        WallTimeLimit                  0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":FileSizeLimit.
    jsdlPOSIX__Limits_USCOREType*        FileSizeLimit                  0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":CoreDumpLimit.
    jsdlPOSIX__Limits_USCOREType*        CoreDumpLimit                  0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":DataSegmentLimit.
    jsdlPOSIX__Limits_USCOREType*        DataSegmentLimit               0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":LockedMemoryLimit.
    jsdlPOSIX__Limits_USCOREType*        LockedMemoryLimit              0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":MemoryLimit.
    jsdlPOSIX__Limits_USCOREType*        MemoryLimit                    0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":OpenDescriptorsLimit.
    jsdlPOSIX__Limits_USCOREType*        OpenDescriptorsLimit           0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":PipeSizeLimit.
    jsdlPOSIX__Limits_USCOREType*        PipeSizeLimit                  0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":StackSizeLimit.
    jsdlPOSIX__Limits_USCOREType*        StackSizeLimit                 0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":CPUTimeLimit.
    jsdlPOSIX__Limits_USCOREType*        CPUTimeLimit                   0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":ProcessCountLimit.
    jsdlPOSIX__Limits_USCOREType*        ProcessCountLimit              0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":VirtualMemoryLimit.
    jsdlPOSIX__Limits_USCOREType*        VirtualMemoryLimit             0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":ThreadCountLimit.
    jsdlPOSIX__Limits_USCOREType*        ThreadCountLimit               0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":UserName.
    jsdlPOSIX__UserName_USCOREType*      UserName                       0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":GroupName.
    jsdlPOSIX__GroupName_USCOREType*     GroupName                      0;	///< Optional element.
/// Attribute name of type xs:NCName.
   @xsd__NCName*                         name                           0;	///< Optional attribute.
/// TODO: <anyAttribute namespace="##other">
///       Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this attribute.
   @_XML                                 __anyAttribute                ;	///< Catch any attribute content in XML string.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://www.nordugrid.org/ws/schemas/jsdl-arc":Version_Type is a complexType.
class jsdlARC__Version_USCOREType
{ public:
/// Element UpperExclusive of type xs:string.
    std::string*                         UpperExclusive                 0;	///< Optional element.
/// Element LowerExclusive of type xs:string.
    std::string*                         LowerExclusive                 0;	///< Optional element.
/// Vector of std::string with length 0..unbounded
    std::vector<std::string            > Exact                          0;
/// Element Exclusive of type xs:boolean.
    bool*                                Exclusive                      0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://www.nordugrid.org/ws/schemas/jsdl-arc":RunTimeEnvironment_Type is a complexType.
class jsdlARC__RunTimeEnvironment_USCOREType
{ public:
/// Element Name of type xs:string.
    std::string                          Name                           1;	///< Required element.
/// Element Version of type "http://www.nordugrid.org/ws/schemas/jsdl-arc":Version_Type.
    jsdlARC__Version_USCOREType*         Version                        0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://www.nordugrid.org/ws/schemas/jsdl-arc":Middleware_Type is a complexType.
class jsdlARC__Middleware_USCOREType
{ public:
/// Element Name of type xs:string.
    std::string                          Name                           1;	///< Required element.
/// Element Version of type "http://www.nordugrid.org/ws/schemas/jsdl-arc":Version_Type.
    jsdlARC__Version_USCOREType*         Version                        0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://www.nordugrid.org/ws/schemas/jsdl-arc":RemoteLogging_Type is a complexType.
class jsdlARC__RemoteLogging_USCOREType
{ public:
/// Element URL of type xs:anyURI.
    xsd__anyURI                          URL                            1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://www.nordugrid.org/ws/schemas/jsdl-arc":CredentialServer_Type is a complexType.
class jsdlARC__CredentialServer_USCOREType
{ public:
/// Element URL of type xs:anyURI.
    xsd__anyURI                          URL                            1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://www.nordugrid.org/ws/schemas/jsdl-arc":LocalLogging_Type is a complexType.
class jsdlARC__LocalLogging_USCOREType
{ public:
/// Element Directory of type xs:string.
    std::string                          Directory                      1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://www.nordugrid.org/ws/schemas/jsdl-arc":AccessControl_Type is a complexType.
class jsdlARC__AccessControl_USCOREType
{ public:
/// Element OwnerAlwaysAllowed of type xs:boolean.
    bool*                                OwnerAlwaysAllowed             0;	///< Optional element.
/// Element Type of type "http://www.nordugrid.org/ws/schemas/jsdl-arc":AccessControlType_Type.
    enum jsdlARC__AccessControlType_USCOREType*  Type                           0;	///< Optional element.
/// Element Content of type xs:string.
    std::string*                         Content                        0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://www.nordugrid.org/ws/schemas/jsdl-arc":Notify_Type is a complexType.
class jsdlARC__Notify_USCOREType
{ public:
/// Element Type of type "http://www.nordugrid.org/ws/schemas/jsdl-arc":NotificationType_Type.
    enum jsdlARC__NotificationType_USCOREType*  Type                           0;	///< Optional element.
/// Element Endpoint of type xs:string.
    std::string*                         Endpoint                       0;	///< Optional element.
/// Vector of enum jsdlARC__GMState_USCOREType with length 1..unbounded
    std::vector<enum jsdlARC__GMState_USCOREType> State                          1;
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://www.nordugrid.org/ws/schemas/jsdl-arc":CandidateTarget_Type is a complexType.
class jsdlARC__CandidateTarget_USCOREType
{ public:
/// Element HostName of type xs:string.
    std::string*                         HostName                       0;	///< Optional element.
/// Element QueueName of type xs:string.
    std::string*                         QueueName                      0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://schemas.ggf.org/jsdl/2005/11/jsdl":Range_Type is a complexType.
class jsdl__Range_USCOREType
{ public:
/// Element LowerBound of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":Boundary_Type.
    jsdl__Boundary_USCOREType*           LowerBound                     1;	///< Required element.
/// Element UpperBound of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":Boundary_Type.
    jsdl__Boundary_USCOREType*           UpperBound                     1;	///< Required element.
/// TODO: <anyAttribute namespace="##other">
///       Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this attribute.
   @_XML                                 __anyAttribute                ;	///< Catch any attribute content in XML string.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://schemas.ggf.org/jsdl/2005/11/jsdl":RangeValue_Type is a complexType.
class jsdl__RangeValue_USCOREType
{ public:
/// Element UpperBoundedRange of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":Boundary_Type.
    jsdl__Boundary_USCOREType*           UpperBoundedRange              0;	///< Optional element.
/// Element LowerBoundedRange of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":Boundary_Type.
    jsdl__Boundary_USCOREType*           LowerBoundedRange              0;	///< Optional element.
/// Vector of jsdl__Exact_USCOREType* with length 0..unbounded
    std::vector<jsdl__Exact_USCOREType*> Exact                          0;
/// Vector of jsdl__Range_USCOREType* with length 0..unbounded
    std::vector<jsdl__Range_USCOREType*> Range                          0;
/// TODO: <anyAttribute namespace="##other">
///       Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this attribute.
   @_XML                                 __anyAttribute                ;	///< Catch any attribute content in XML string.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://schemas.ggf.org/jsdl/2005/11/jsdl":JobDefinition_Type is a complexType.
class jsdl__JobDefinition_USCOREType
{ public:
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":JobDescription.
    jsdl__JobDescription_USCOREType*     JobDescription                 1;	///< Required element.
/// TODO: <any namespace="##other" minOccurs="0" maxOccurs="unbounded">
///       Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this element.
///       Use wsdl2h option -d to use xsd__anyType DOM.
    std::vector<_XML>                    __any                         ;	///< Catch any element content in XML string.
/// Attribute id of type xs:ID.
   @xsd__ID*                             id                             0;	///< Optional attribute.
/// TODO: <anyAttribute namespace="##other">
///       Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this attribute.
   @_XML                                 __anyAttribute                ;	///< Catch any attribute content in XML string.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://schemas.ggf.org/jsdl/2005/11/jsdl":JobDescription_Type is a complexType.
class jsdl__JobDescription_USCOREType
{ public:
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":JobIdentification.
    jsdl__JobIdentification_USCOREType*  JobIdentification              0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":Application.
    jsdl__Application_USCOREType*        Application                    0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":Resources.
    jsdl__Resources_USCOREType*          Resources                      0;	///< Optional element.
/// Vector of jsdl__DataStaging_USCOREType* with length 0..unbounded
    std::vector<jsdl__DataStaging_USCOREType*> DataStaging                    0;
/// Vector of jsdlARC__Notify_USCOREType* with length 0..3
    std::vector<jsdlARC__Notify_USCOREType*> jsdlARC__Notify                0:3;
/// Element reference "http://www.nordugrid.org/ws/schemas/jsdl-arc":AccessControl.
    jsdlARC__AccessControl_USCOREType*   jsdlARC__AccessControl         0;	///< Optional element.
/// Element reference "http://www.nordugrid.org/ws/schemas/jsdl-arc":LocalLogging.
    jsdlARC__LocalLogging_USCOREType*    jsdlARC__LocalLogging          0;	///< Optional element.
/// Vector of jsdlARC__RemoteLogging_USCOREType* with length 0..3
    std::vector<jsdlARC__RemoteLogging_USCOREType*> jsdlARC__RemoteLogging         0:3;
/// Element reference "http://www.nordugrid.org/ws/schemas/jsdl-arc":CredentialServer.
    jsdlARC__CredentialServer_USCOREType*  jsdlARC__CredentialServer      0;	///< Optional element.
/// Element reference "http://www.nordugrid.org/ws/schemas/jsdl-arc":Reruns.
    jsdlARC__Reruns_USCOREType*          jsdlARC__Reruns                0;	///< Optional element.
/// Element reference "http://www.nordugrid.org/ws/schemas/jsdl-arc":ProcessingStartTime.
    jsdlARC__Time_USCOREType*            jsdlARC__ProcessingStartTime   0;	///< Optional element.
/// Vector of jsdl__JobDescription_USCOREType* with length 0..unbounded
    std::vector<jsdl__JobDescription_USCOREType*> JobDescription                 0;
/// TODO: <any namespace="##other" minOccurs="0" maxOccurs="unbounded">
///       Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this element.
///       Use wsdl2h option -d to use xsd__anyType DOM.
    std::vector<_XML>                    __any                         ;	///< Catch any element content in XML string.
/// TODO: <anyAttribute namespace="##other">
///       Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this attribute.
   @_XML                                 __anyAttribute                ;	///< Catch any attribute content in XML string.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://schemas.ggf.org/jsdl/2005/11/jsdl":JobIdentification_Type is a complexType.
class jsdl__JobIdentification_USCOREType
{ public:
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":JobName.
    std::string*                         JobName                        0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":Description.
    jsdl__Description_USCOREType*        Description                    0;	///< Optional element.
/// Vector of std::string with length 0..unbounded
    std::vector<std::string            > JobAnnotation                  0;
/// Vector of std::string with length 0..unbounded
    std::vector<std::string            > JobProject                     0;
/// TODO: <any namespace="##other" minOccurs="0" maxOccurs="unbounded">
///       Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this element.
///       Use wsdl2h option -d to use xsd__anyType DOM.
    std::vector<_XML>                    __any                         ;	///< Catch any element content in XML string.
/// TODO: <anyAttribute namespace="##other">
///       Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this attribute.
   @_XML                                 __anyAttribute                ;	///< Catch any attribute content in XML string.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://schemas.ggf.org/jsdl/2005/11/jsdl":Application_Type is a complexType.
class jsdl__Application_USCOREType
{ public:
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":ApplicationName.
    std::string*                         ApplicationName                0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":ApplicationVersion.
    std::string*                         ApplicationVersion             0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":Description.
    jsdl__Description_USCOREType*        Description                    0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":POSIXApplication.
    jsdlPOSIX__POSIXApplication_USCOREType*  jsdlPOSIX__POSIXApplication    0;	///< Optional element.
/// TODO: <any namespace="##other" minOccurs="0" maxOccurs="unbounded">
///       Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this element.
///       Use wsdl2h option -d to use xsd__anyType DOM.
    std::vector<_XML>                    __any                         ;	///< Catch any element content in XML string.
/// TODO: <anyAttribute namespace="##other">
///       Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this attribute.
   @_XML                                 __anyAttribute                ;	///< Catch any attribute content in XML string.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://schemas.ggf.org/jsdl/2005/11/jsdl":Resources_Type is a complexType.
class jsdl__Resources_USCOREType
{ public:
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":CandidateHosts.
    jsdl__CandidateHosts_USCOREType*     CandidateHosts                 0;	///< Optional element.
/// Vector of jsdl__FileSystem_USCOREType* with length 0..unbounded
    std::vector<jsdl__FileSystem_USCOREType*> FileSystem                     0;
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":ExclusiveExecution.
    bool*                                ExclusiveExecution             0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":OperatingSystem.
    jsdl__OperatingSystem_USCOREType*    OperatingSystem                0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":CPUArchitecture.
    jsdl__CPUArchitecture_USCOREType*    CPUArchitecture                0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":IndividualCPUSpeed.
    jsdl__RangeValue_USCOREType*         IndividualCPUSpeed             0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":IndividualCPUTime.
    jsdl__RangeValue_USCOREType*         IndividualCPUTime              0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":IndividualCPUCount.
    jsdl__RangeValue_USCOREType*         IndividualCPUCount             0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":IndividualNetworkBandwidth.
    jsdl__RangeValue_USCOREType*         IndividualNetworkBandwidth     0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":IndividualPhysicalMemory.
    jsdl__RangeValue_USCOREType*         IndividualPhysicalMemory       0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":IndividualVirtualMemory.
    jsdl__RangeValue_USCOREType*         IndividualVirtualMemory        0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":IndividualDiskSpace.
    jsdl__RangeValue_USCOREType*         IndividualDiskSpace            0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":TotalCPUTime.
    jsdl__RangeValue_USCOREType*         TotalCPUTime                   0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":TotalCPUCount.
    jsdl__RangeValue_USCOREType*         TotalCPUCount                  0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":TotalPhysicalMemory.
    jsdl__RangeValue_USCOREType*         TotalPhysicalMemory            0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":TotalVirtualMemory.
    jsdl__RangeValue_USCOREType*         TotalVirtualMemory             0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":TotalDiskSpace.
    jsdl__RangeValue_USCOREType*         TotalDiskSpace                 0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":TotalResourceCount.
    jsdl__RangeValue_USCOREType*         TotalResourceCount             0;	///< Optional element.
/// Element reference "http://www.nordugrid.org/ws/schemas/jsdl-arc":SessionLifeTime.
    jsdlARC__SessionLifeTime_USCOREType*  jsdlARC__SessionLifeTime       0;	///< Optional element.
/// Element reference "http://www.nordugrid.org/ws/schemas/jsdl-arc":SessionType.
    enum jsdlARC__SessionType_USCOREType*  jsdlARC__SessionType           0;	///< Optional element.
/// Element reference "http://www.nordugrid.org/ws/schemas/jsdl-arc":GridTimeLimit.
    jsdlARC__GridTimeLimit_USCOREType*   jsdlARC__GridTimeLimit         0;	///< Optional element.
/// Element reference "http://www.nordugrid.org/ws/schemas/jsdl-arc":CandidateTarget.
    jsdlARC__CandidateTarget_USCOREType*  jsdlARC__CandidateTarget       0;	///< Optional element.
/// Vector of jsdlARC__Middleware_USCOREType* with length 0..unbounded
    std::vector<jsdlARC__Middleware_USCOREType*> jsdlARC__Middleware            0;
/// Vector of jsdlARC__RunTimeEnvironment_USCOREType* with length 0..unbounded
    std::vector<jsdlARC__RunTimeEnvironment_USCOREType*> jsdlARC__RunTimeEnvironment    0;
/// TODO: <any namespace="##other" minOccurs="0" maxOccurs="unbounded">
///       Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this element.
///       Use wsdl2h option -d to use xsd__anyType DOM.
    std::vector<_XML>                    __any                         ;	///< Catch any element content in XML string.
/// TODO: <anyAttribute namespace="##other">
///       Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this attribute.
   @_XML                                 __anyAttribute                ;	///< Catch any attribute content in XML string.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://schemas.ggf.org/jsdl/2005/11/jsdl":CandidateHosts_Type is a complexType.
class jsdl__CandidateHosts_USCOREType
{ public:
/// Vector of std::string with length 1..unbounded
    std::vector<std::string            > HostName                       1;
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://schemas.ggf.org/jsdl/2005/11/jsdl":CPUArchitecture_Type is a complexType.
class jsdl__CPUArchitecture_USCOREType
{ public:
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":CPUArchitectureName.
    enum jsdl__ProcessorArchitectureEnumeration  CPUArchitectureName            1;	///< Required element.
/// TODO: <any namespace="##other" minOccurs="0" maxOccurs="unbounded">
///       Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this element.
///       Use wsdl2h option -d to use xsd__anyType DOM.
    std::vector<_XML>                    __any                         ;	///< Catch any element content in XML string.
/// TODO: <anyAttribute namespace="##other">
///       Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this attribute.
   @_XML                                 __anyAttribute                ;	///< Catch any attribute content in XML string.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://schemas.ggf.org/jsdl/2005/11/jsdl":FileSystem_Type is a complexType.
class jsdl__FileSystem_USCOREType
{ public:
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":FileSystemType.
    enum jsdl__FileSystemTypeEnumeration*  FileSystemType                 0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":Description.
    jsdl__Description_USCOREType*        Description                    0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":MountPoint.
    std::string*                         MountPoint                     0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":DiskSpace.
    jsdl__RangeValue_USCOREType*         DiskSpace                      0;	///< Optional element.
/// TODO: <any namespace="##other" minOccurs="0" maxOccurs="unbounded">
///       Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this element.
///       Use wsdl2h option -d to use xsd__anyType DOM.
    std::vector<_XML>                    __any                         ;	///< Catch any element content in XML string.
/// Attribute name of type xs:NCName.
   @xsd__NCName                          name                           1;	///< Required attribute.
/// TODO: <anyAttribute namespace="##other">
///       Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this attribute.
   @_XML                                 __anyAttribute                ;	///< Catch any attribute content in XML string.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://schemas.ggf.org/jsdl/2005/11/jsdl":OperatingSystem_Type is a complexType.
class jsdl__OperatingSystem_USCOREType
{ public:
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":OperatingSystemType.
    jsdl__OperatingSystemType_USCOREType*  OperatingSystemType            0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":OperatingSystemVersion.
    std::string*                         OperatingSystemVersion         0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":Description.
    jsdl__Description_USCOREType*        Description                    0;	///< Optional element.
/// TODO: <any namespace="##other" minOccurs="0" maxOccurs="unbounded">
///       Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this element.
///       Use wsdl2h option -d to use xsd__anyType DOM.
    std::vector<_XML>                    __any                         ;	///< Catch any element content in XML string.
/// TODO: <anyAttribute namespace="##other">
///       Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this attribute.
   @_XML                                 __anyAttribute                ;	///< Catch any attribute content in XML string.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://schemas.ggf.org/jsdl/2005/11/jsdl":OperatingSystemType_Type is a complexType.
class jsdl__OperatingSystemType_USCOREType
{ public:
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":OperatingSystemName.
    enum jsdl__OperatingSystemTypeEnumeration  OperatingSystemName            1;	///< Required element.
/// TODO: <any namespace="##other" minOccurs="0" maxOccurs="unbounded">
///       Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this element.
///       Use wsdl2h option -d to use xsd__anyType DOM.
    std::vector<_XML>                    __any                         ;	///< Catch any element content in XML string.
/// TODO: <anyAttribute namespace="##other">
///       Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this attribute.
   @_XML                                 __anyAttribute                ;	///< Catch any attribute content in XML string.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://schemas.ggf.org/jsdl/2005/11/jsdl":DataStaging_Type is a complexType.
class jsdl__DataStaging_USCOREType
{ public:
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":FileName.
    std::string                          FileName                       1;	///< Required element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":FilesystemName.
    xsd__NCName*                         FilesystemName                 0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":CreationFlag.
    enum jsdl__CreationFlagEnumeration   CreationFlag                   1;	///< Required element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":DeleteOnTermination.
    bool*                                DeleteOnTermination            0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":Source.
    jsdl__SourceTarget_USCOREType*       Source                         0;	///< Optional element.
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":Target.
    jsdl__SourceTarget_USCOREType*       Target                         0;	///< Optional element.
/// Element reference "http://www.nordugrid.org/ws/schemas/jsdl-arc":IsExecutable.
    jsdlARC__IsExecutable_USCOREType*    jsdlARC__IsExecutable          0;	///< Optional element.
/// Element reference "http://www.nordugrid.org/ws/schemas/jsdl-arc":FileParameters.
    jsdlARC__FileParameters_USCOREType*  jsdlARC__FileParameters        0;	///< Optional element.
/// TODO: <any namespace="##other" minOccurs="0" maxOccurs="unbounded">
///       Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this element.
///       Use wsdl2h option -d to use xsd__anyType DOM.
    std::vector<_XML>                    __any                         ;	///< Catch any element content in XML string.
/// Attribute name of type xs:NCName.
   @xsd__NCName*                         name                           0;	///< Optional attribute.
/// TODO: <anyAttribute namespace="##other">
///       Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this attribute.
   @_XML                                 __anyAttribute                ;	///< Catch any attribute content in XML string.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://schemas.ggf.org/jsdl/2005/11/jsdl":SourceTarget_Type is a complexType.
class jsdl__SourceTarget_USCOREType
{ public:
/// Element reference "http://schemas.ggf.org/jsdl/2005/11/jsdl":URI.
    xsd__anyURI*                         URI                            0;	///< Optional element.
/// TODO: <any namespace="##other" minOccurs="0" maxOccurs="unbounded">
///       Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this element.
///       Use wsdl2h option -d to use xsd__anyType DOM.
    std::vector<_XML>                    __any                         ;	///< Catch any element content in XML string.
/// TODO: <anyAttribute namespace="##other">
///       Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this attribute.
   @_XML                                 __anyAttribute                ;	///< Catch any attribute content in XML string.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":Environment_Type is a complexType with simpleContent.
class jsdlPOSIX__Environment_USCOREType
{ public:
/// __item wraps 'xs:string' simpleContent.
    std::string                          __item                        ;
/// Attribute name of type xs:NCName.
   @xsd__NCName                          name                           1;	///< Required attribute.
/// Attribute filesystemName of type xs:NCName.
   @xsd__NCName*                         filesystemName                 0;	///< Optional attribute.
/// TODO: <anyAttribute namespace="##other">
///       Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this attribute.
   @_XML                                 __anyAttribute                ;	///< Catch any attribute content in XML string.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":Argument_Type is a complexType with simpleContent.
class jsdlPOSIX__Argument_USCOREType
{ public:
/// __item wraps 'xs:normalizedString' simpleContent.
    xsd__normalizedString                __item                        ;
/// Attribute filesystemName of type xs:NCName.
   @xsd__NCName*                         filesystemName                 0;	///< Optional attribute.
/// TODO: <anyAttribute namespace="##other">
///       Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this attribute.
   @_XML                                 __anyAttribute                ;	///< Catch any attribute content in XML string.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":FileName_Type is a complexType with simpleContent.
class jsdlPOSIX__FileName_USCOREType
{ public:
/// __item wraps 'xs:string' simpleContent.
    std::string                          __item                        ;
/// Attribute filesystemName of type xs:NCName.
   @xsd__NCName*                         filesystemName                 0;	///< Optional attribute.
/// TODO: <anyAttribute namespace="##other">
///       Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this attribute.
   @_XML                                 __anyAttribute                ;	///< Catch any attribute content in XML string.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":DirectoryName_Type is a complexType with simpleContent.
class jsdlPOSIX__DirectoryName_USCOREType
{ public:
/// __item wraps 'xs:string' simpleContent.
    std::string                          __item                        ;
/// Attribute filesystemName of type xs:NCName.
   @xsd__NCName*                         filesystemName                 0;	///< Optional attribute.
/// TODO: <anyAttribute namespace="##other">
///       Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this attribute.
   @_XML                                 __anyAttribute                ;	///< Catch any attribute content in XML string.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":Limits_Type is a complexType with simpleContent.
class jsdlPOSIX__Limits_USCOREType
{ public:
/// __item wraps 'xs:nonNegativeInteger' simpleContent.
    unsigned int                         __item                        ;
/// TODO: <anyAttribute namespace="##other">
///       Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this attribute.
   @_XML                                 __anyAttribute                ;	///< Catch any attribute content in XML string.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":UserName_Type is a complexType with simpleContent.
class jsdlPOSIX__UserName_USCOREType
{ public:
/// __item wraps 'xs:string' simpleContent.
    std::string                          __item                        ;
/// TODO: <anyAttribute namespace="##other">
///       Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this attribute.
   @_XML                                 __anyAttribute                ;	///< Catch any attribute content in XML string.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":GroupName_Type is a complexType with simpleContent.
class jsdlPOSIX__GroupName_USCOREType
{ public:
/// __item wraps 'xs:string' simpleContent.
    std::string                          __item                        ;
/// TODO: <anyAttribute namespace="##other">
///       Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this attribute.
   @_XML                                 __anyAttribute                ;	///< Catch any attribute content in XML string.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://schemas.ggf.org/jsdl/2005/11/jsdl":Boundary_Type is a complexType with simpleContent.
class jsdl__Boundary_USCOREType
{ public:
/// __item wraps 'xs:double' simpleContent.
    double                               __item                        ;
/// Attribute exclusiveBound of type xs:boolean.
   @bool*                                exclusiveBound                 0;	///< Optional attribute.
/// TODO: <anyAttribute namespace="##other">
///       Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this attribute.
   @_XML                                 __anyAttribute                ;	///< Catch any attribute content in XML string.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://schemas.ggf.org/jsdl/2005/11/jsdl":Exact_Type is a complexType with simpleContent.
class jsdl__Exact_USCOREType
{ public:
/// __item wraps 'xs:double' simpleContent.
    double                               __item                        ;
/// Attribute epsilon of type xs:double.
   @double*                              epsilon                        0;	///< Optional attribute.
/// TODO: <anyAttribute namespace="##other">
///       Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this attribute.
   @_XML                                 __anyAttribute                ;	///< Catch any attribute content in XML string.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":POSIXApplication of type "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":POSIXApplication_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":Executable of type "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":FileName_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":Argument of type "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":Argument_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":Input of type "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":FileName_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":Output of type "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":FileName_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":Error of type "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":FileName_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":WorkingDirectory of type "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":DirectoryName_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":Environment of type "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":Environment_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":WallTimeLimit of type "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":Limits_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":FileSizeLimit of type "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":Limits_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":CoreDumpLimit of type "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":Limits_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":DataSegmentLimit of type "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":Limits_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":LockedMemoryLimit of type "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":Limits_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":MemoryLimit of type "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":Limits_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":OpenDescriptorsLimit of type "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":Limits_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":PipeSizeLimit of type "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":Limits_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":StackSizeLimit of type "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":Limits_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":CPUTimeLimit of type "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":Limits_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":ProcessCountLimit of type "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":Limits_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":VirtualMemoryLimit of type "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":Limits_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":ThreadCountLimit of type "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":Limits_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":UserName of type "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":UserName_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":GroupName of type "http://schemas.ggf.org/jsdl/2005/11/jsdl-posix":GroupName_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://www.nordugrid.org/ws/schemas/jsdl-arc":IsExecutable of type "http://www.nordugrid.org/ws/schemas/jsdl-arc":IsExecutable_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://www.nordugrid.org/ws/schemas/jsdl-arc":FileParameters of type "http://www.nordugrid.org/ws/schemas/jsdl-arc":FileParameters_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://www.nordugrid.org/ws/schemas/jsdl-arc":RunTimeEnvironment of type "http://www.nordugrid.org/ws/schemas/jsdl-arc":RunTimeEnvironment_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://www.nordugrid.org/ws/schemas/jsdl-arc":Middleware of type "http://www.nordugrid.org/ws/schemas/jsdl-arc":Middleware_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://www.nordugrid.org/ws/schemas/jsdl-arc":RemoteLogging of type "http://www.nordugrid.org/ws/schemas/jsdl-arc":RemoteLogging_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://www.nordugrid.org/ws/schemas/jsdl-arc":LocalLogging of type "http://www.nordugrid.org/ws/schemas/jsdl-arc":LocalLogging_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://www.nordugrid.org/ws/schemas/jsdl-arc":AccessControl of type "http://www.nordugrid.org/ws/schemas/jsdl-arc":AccessControl_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://www.nordugrid.org/ws/schemas/jsdl-arc":Notify of type "http://www.nordugrid.org/ws/schemas/jsdl-arc":Notify_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://www.nordugrid.org/ws/schemas/jsdl-arc":SessionLifeTime of type "http://www.nordugrid.org/ws/schemas/jsdl-arc":SessionLifeTime_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://www.nordugrid.org/ws/schemas/jsdl-arc":SessionType of type "http://www.nordugrid.org/ws/schemas/jsdl-arc":SessionType_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://www.nordugrid.org/ws/schemas/jsdl-arc":JoinOutputs of type "http://www.nordugrid.org/ws/schemas/jsdl-arc":JoinOutputs_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://www.nordugrid.org/ws/schemas/jsdl-arc":Reruns of type "http://www.nordugrid.org/ws/schemas/jsdl-arc":Reruns_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://www.nordugrid.org/ws/schemas/jsdl-arc":CredentialServer of type "http://www.nordugrid.org/ws/schemas/jsdl-arc":CredentialServer_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://www.nordugrid.org/ws/schemas/jsdl-arc":GridTimeLimit of type "http://www.nordugrid.org/ws/schemas/jsdl-arc":GridTimeLimit_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://www.nordugrid.org/ws/schemas/jsdl-arc":CandidateTarget of type "http://www.nordugrid.org/ws/schemas/jsdl-arc":CandidateTarget_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://www.nordugrid.org/ws/schemas/jsdl-arc":ProcessingStartTime of type "http://www.nordugrid.org/ws/schemas/jsdl-arc":Time_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":JobDefinition of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":JobDefinition_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":JobDescription of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":JobDescription_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":JobIdentification of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":JobIdentification_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":JobName of type xs:string.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":Description of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":Description_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":JobAnnotation of type xs:string.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":JobProject of type xs:string.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":Application of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":Application_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":ApplicationName of type xs:string.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":ApplicationVersion of type xs:string.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":Resources of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":Resources_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":CandidateHosts of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":CandidateHosts_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":HostName of type xs:string.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":OperatingSystem of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":OperatingSystem_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":OperatingSystemType of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":OperatingSystemType_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":OperatingSystemVersion of type xs:string.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":OperatingSystemName of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":OperatingSystemTypeEnumeration.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":ExclusiveExecution of type xs:boolean.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":CPUArchitecture of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":CPUArchitecture_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":CPUArchitectureName of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":ProcessorArchitectureEnumeration.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":FileSystem of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":FileSystem_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":FileSystemType of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":FileSystemTypeEnumeration.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":MountPoint of type xs:string.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":DiskSpace of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":RangeValue_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":IndividualCPUTime of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":RangeValue_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":IndividualCPUSpeed of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":RangeValue_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":IndividualCPUCount of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":RangeValue_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":IndividualPhysicalMemory of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":RangeValue_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":IndividualVirtualMemory of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":RangeValue_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":IndividualNetworkBandwidth of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":RangeValue_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":IndividualDiskSpace of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":RangeValue_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":TotalCPUTime of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":RangeValue_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":TotalCPUCount of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":RangeValue_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":TotalPhysicalMemory of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":RangeValue_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":TotalVirtualMemory of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":RangeValue_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":TotalDiskSpace of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":RangeValue_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":TotalResourceCount of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":RangeValue_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":DataStaging of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":DataStaging_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":FileName of type xs:string.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":FilesystemName of type xs:NCName.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":CreationFlag of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":CreationFlagEnumeration.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":DeleteOnTermination of type xs:boolean.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":Source of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":SourceTarget_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":Target of type "http://schemas.ggf.org/jsdl/2005/11/jsdl":SourceTarget_Type.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.ggf.org/jsdl/2005/11/jsdl":URI of type xs:anyURI.
/// Note: use wsdl2h option -g to generate this global element declaration.

/* End of jsdl_soap.h */
