include install.mk

clean-local:
	rm -rf build src/pyarcrest.egg-info

EXTRA_DIST = \
	README.md \
	setup.cfg \
	setup.py \
	src/pyarcrest/arc.py \
	src/pyarcrest/cli/__init__.py \
	src/pyarcrest/cli/arcrest.py \
	src/pyarcrest/errors.py \
	src/pyarcrest/__init__.py \
	src/pyarcrest/http.py \
	src/pyarcrest/x509.py
