debian/tmp/usr/share/arc/ldap-schema/nordugrid.schema
debian/tmp/usr/share/arc/ldap-schema/glue-1.2/Glue-SE.schema
debian/tmp/usr/share/arc/ldap-schema/glue-1.2/Glue-CE.schema
debian/tmp/usr/share/arc/ldap-schema/glue-1.2/Glue-MDS.schema
debian/tmp/usr/share/arc/ldap-schema/glue-1.2/Glue-CORE.schema
debian/tmp/usr/share/arc/ldap-schema/glue-1.2/Glue-CESEBind.schema

debian/tmp/usr/lib/arc/grid-info-soft-register

debian/tmp/usr/lib/arc/glue-generator.pl
debian/tmp/usr/lib/arc/qju.pl
debian/tmp/usr/lib/arc/cluster.pl
debian/tmp/usr/lib/arc/se.pl

debian/tmp/usr/lib/arc/LRMS.pm
debian/tmp/usr/lib/arc/Shared.pm
debian/tmp/usr/lib/arc/ConfigParser.pm
debian/tmp/usr/lib/arc/LogUtils.pm

debian/tmp/usr/lib/arc/grid-infosys-bdii5
debian/tmp/usr/lib/arc/grid-infosys-bdii4
debian/tmp/etc/init.d/a-rex-grid-infosys
