debian/tmp/usr/share/arc/ldap-schema/nordugrid.schema
debian/tmp/usr/share/arc/ldap-schema/glue-1.2/Glue-SE.schema
debian/tmp/usr/share/arc/ldap-schema/glue-1.2/Glue-CE.schema
debian/tmp/usr/share/arc/ldap-schema/glue-1.2/Glue-MDS.schema
debian/tmp/usr/share/arc/ldap-schema/glue-1.2/Glue-CORE.schema
debian/tmp/usr/share/arc/ldap-schema/glue-1.2/Glue-CESEBind.schema

debian/tmp/usr/share/arc/grid-info-soft-register

debian/tmp/usr/share/arc/glue-generator.pl
debian/tmp/usr/share/arc/glite-info-provider-ldap
debian/tmp/usr/share/arc/qju.pl
debian/tmp/usr/share/arc/cluster.pl
debian/tmp/usr/share/arc/se.pl

debian/tmp/usr/share/arc/LRMS.pm
debian/tmp/usr/share/arc/Shared.pm
debian/tmp/usr/share/arc/ConfigParser.pm

debian/tmp/usr/share/arc/grid-infosys-bdii5
debian/tmp/usr/share/arc/grid-infosys-bdii4
