/usr/lib/python?.*/site-packages/arc/control/Cleanup.py
/usr/lib/python?.*/site-packages/arc/control/Config.py
/usr/lib/python?.*/site-packages/arc/control/OSService.py
/usr/lib/python?.*/site-packages/arc/control/ServiceCommon.py
/usr/lib/python?.*/site-packages/arc/control/Services.py
/usr/lib/python?.*/site-packages/arc/control/Validator.py

/usr/lib/python?.*/site-packages/arc/control/__pycache__/Cleanup.*
/usr/lib/python?.*/site-packages/arc/control/__pycache__/Config.*
/usr/lib/python?.*/site-packages/arc/control/__pycache__/OSService.*
/usr/lib/python?.*/site-packages/arc/control/__pycache__/ServiceCommon.*
/usr/lib/python?.*/site-packages/arc/control/__pycache__/Services.*
/usr/lib/python?.*/site-packages/arc/control/__pycache__/Validator.*
