debian/tmp/usr/lib/python?.?/site-packages/arc/control/__init__.py*
debian/tmp/usr/lib/python?.?/site-packages/arc/control/CertificateGenerator.py*
debian/tmp/usr/lib/python?.?/site-packages/arc/control/ControlCommon.py*
debian/tmp/usr/lib/python?.?/site-packages/arc/control/OSPackage.py*
debian/tmp/usr/lib/python?.?/site-packages/arc/control/OSService.py*
debian/tmp/usr/lib/python?.?/site-packages/arc/control/TestCA.py*
debian/tmp/usr/lib/python?.?/site-packages/arc/control/ThirdPartyDeployment.py*

debian/tmp/usr/share/man/man1/arcctl.1

debian/tmp/usr/sbin/arcctl

