debian/tmp/usr/share/arc/ldap-schema/nordugrid.schema

debian/tmp/usr/share/arc/grid-info-soft-register

debian/tmp/usr/share/arc/glue-generator.pl
debian/tmp/usr/share/arc/glite-info-provider-ldap
debian/tmp/usr/share/arc/qju.pl
debian/tmp/usr/share/arc/cluster.pl
debian/tmp/usr/share/arc/se.pl

debian/tmp/usr/share/arc/LRMS.pm
debian/tmp/usr/share/arc/Shared.pm
debian/tmp/usr/share/arc/ConfigParser.pm
debian/tmp/usr/share/arc/config_parser_compat.sh
