#!/usr/bin/python2
import sys

try:
    from arc.lrms import pySubmit
except:
    sys.stderr.write('Failed to import pySubmit module\n')
    sys.exit(2)


if __name__ == '__main__':
    usage = 'Usage: %s [--config <arc.conf>] <grami>' % (sys.argv[0])

    if len(sys.argv) != 4 and len(sys.argv) != 2:
        error(usage, 'submit-SLURMPY-job')
        sys.exit(1)

    if len(sys.argv) == 4:
        if sys.argv[1] != "--config":
            error(usage, 'submit-SLURMPY-job')
            sys.exit(1)
        sys.exit(pySubmit.main("slurm", sys.argv[3], sys.argv[2]))

    sys.exit(pySubmit.main("slurm", sys.argv[1]))
