.\" -*- nroff -*-
.TH APPROXY "23" "February 2008" "NorduGrid ARC 0.9.0" "NorduGrid System Manager's Manual"
.SH NAME
approxy \- ARC Credentials Proxy generation utility
.SH SYNOPSIS
.B approxy
[\fIOPTION\fR]
.SH DESCRIPTION
.\" Add any additional description here
.PP
approxy generates proxy credentials from private key and certificate of user.
.SH OPTIONS
.TP
\fB\-d\fR
level of information printed. Possible values are VERBOSE, DEBUG, INFO, WARNING, ERROR and FATAL.
.TP
\fB\-l\fR
full path to log file. If missing all messages are printed to stderr.
.TP
\fB\-P\fR
location of generated credentials proxy file
.TP
\fB\-C\fR
location of X509 certificate file
.TP
\fB\-K\fR
location of private key file
.TP
\fB\-c\fR
constraints of proxy certificate. Currently following constraints are supported:

\fBvalidityStart=time\fR - time when certificate becomes valid. Default is now.

\fBvalidityEnd=time\fR - time when certificate becomes invalid valid. Default is equal 
to one specified in source certificate.

\fBvalidityPeriod=time\fR - for how long certificate is valid.

\fBproxyPolicy=policy content\fR - assigns specified string to proxy prolicy to limit it's functionality.
.TP
\fB\-h\fR
prints short usage description
.PP
If not specified location of certificate, key and proxy will be taken from content of environment
variables X509_USER_CERT, X509_USER_KEY and X509_USER_PROXY.
.SH "REPORTING BUGS"
Report bugs to http://bugzilla.nordugrid.org/
.SH COPYRIGHT
We need to have this
.SH FILES
.SH AUTHOR
Written by developers
