#!/bin/bash
if [ "$#" == "0" ]
then
    echo "USAGE:"
    echo "  storage hash|catalog|manager <command> <arguments>"
    exit 1
fi
if [ "$1" == "hash" ]
then
    shift
    python hash_client.py $*
elif [ "$1" == "catalog" ]
then
    shift
    python catalog_client.py $*
elif [ "$1" == "manager" ]
then
    shift
    python manager_client.py $*
elif [ "$1" == "element" ]
then
    shift
    python element_client.py $*
fi
