#!/bin/bash
export PYTHONPATH=./arc1/src/services:./arc1/python:./arc1/python/.libs
if [ "$1" == "hash" ]
then
    shift
    python ./arc1/src/services/storage/cli/hash_client.py $*
elif [ "$1" == "librarian" ]
then
    shift
    python ./arc1/src/services/storage/cli/librarian_client.py $*
elif [ "$1" == "manager" ]
then
    shift
    python ./arc1/src/services/storage/cli/manager_client.py $*
elif [ "$1" == "element" ]
then
    shift
    python ./arc1/src/services/storage/cli/element_client.py $*
else
    echo "USAGE:"
    echo "  storage hash|librarian|manager|element <command> <arguments>"
    exit 1
fi
