#!/bin/bash
export PYTHONPATH=./arc1/src/services:./arc1/python:./arc1/python/.libs
if [ "$1" == "ahash" ]
then
    shift
    python ./arc1/src/services/storage/cli/ahash_client.py $*
elif [ "$1" == "librarian" ]
then
    shift
    python ./arc1/src/services/storage/cli/librarian_client.py $*
elif [ "$1" == "bartender" ]
then
    shift
    python ./arc1/src/services/storage/cli/bartender_client.py $*
elif [ "$1" == "element" ]
then
    shift
    python ./arc1/src/services/storage/cli/element_client.py $*
else
    echo "USAGE:"
    echo "  storage ahash|librarian|bartender|element <command> <arguments>"
    exit 1
fi
