#!/bin/sh -f
# 
#  Cancel job running in LoadLeveler.
#

progname=`basename $0`
echo "----- starting $progname -----" 1>&2

joboption_lrms=ll

basedir=`dirname $0`
basedir=`cd $basedir; pwd`

. ${basedir}/cancel_common.sh $1

LL_DEL='llcancel'
if [ ! -z "$LL_BIN_PATH" ] ; then
  LL_DEL="${LL_BIN_PATH}/${LL_DEL}"
fi

echo executing job removal with job id $joboption_jobid 1>&2
"${LL_DEL}" "${joboption_jobid}"

echo "----- exiting $progname -----" 1>&2
echo "" 1>&2
exit 0


