#! /bin/sh -f
# set -x
# 
#  Cancel job running in LoadLeveler.
#

echo "----- starting cancel_ll_job -----" 1>&2

joboption_lrms=ll

. ${ARC_LOCATION}/libexec/cancel_common.sh $1

LL_DEL='llcancel'
if [ ! -z "$LL_BIN_PATH" ] ; then
  LL_DEL="${LL_BIN_PATH}/${LL_DEL}"
fi

echo executing job removal with job id $joboption_jobid 1>&2
"${LL_DEL}" "${joboption_jobid}"

echo "----- exiting cancel_ll_job -----" 1>&2
echo "" 1>&2
exit 0


